## Lab 7. Neuroevolution

To illustrate the work of the NEAT algorithm, we will use some modified examples from the neat-python library http://neat-python.readthedocs.io/en/latest/index.html

We will also use material from the book "Hands-On Machine Learning with Scikit-Learn and TensorFlow. Concepts, Tools, and Techniques to Build Intelligent Systems" by Aurélien Géron, that it is recommended as Bibliography of the course. http://shop.oreilly.com/product/0636920052289.do 

In [1]:
# We start by importing the python libraries required to solve the problems

import os
# supress tensorflow logging other than errors
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

import numpy as np
import neat
import random
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import tensorflow as tf
from keras.datasets import mnist
from sklearn.preprocessing import OneHotEncoder

/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
/usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/dtypes.py:526: FutureWarning: Passing (type, 1) or 

## Neuroevolution NEAT

Neuroevolution studies the study of evolutionary algorithms for the automatic generation of neural networks (architecture and weights).

NEAT is a particular class of neuro-evolutionary algorithm. You can read the two slides from the Lecture that introduce and explain the main characteristics of NEAT. 

neat-python is a library that allows the automatic generation of neural networks. You can read a 3-minutes NEAT overview here: http://neat-python.readthedocs.io/en/latest/neat_overview.html

In order to use NEAT to solve a problem with an evolved NN, the user should define which are the input variables of the network and the output variables. Another essential part is defining the fitness function   that specifies how to evaluate the "quality" of a given NN to solve the problem at hand.


The example below contains the implementation of a neat-python approach for solving the XOR problem. You can find a description of this example here: http://neat-python.readthedocs.io/en/latest/xor_example.html#

Read the explanation of the example and run the following cell. 

In [2]:
"""
2-input XOR example -- this is most likely the simplest possible example.
"""

from __future__ import print_function
import neat

# 2-input XOR inputs and expected outputs.
xor_inputs = [(0.0, 0.0), (0.0, 1.0), (1.0, 0.0), (1.0, 1.0)]
xor_outputs = [   (0.0,),     (1.0,),     (1.0,),     (0.0,)]


number_generations = 100

def eval_genomes(genomes, config):
    for genome_id, genome in genomes:
        genome.fitness = 4.0
        net = neat.nn.FeedForwardNetwork.create(genome, config)
        
        for xi, xo in zip(xor_inputs, xor_outputs):
            output = net.activate(xi)
            genome.fitness -= (output[0] - xo[0]) ** 2


# Load configuration.
config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction, neat.DefaultSpeciesSet, neat.DefaultStagnation,
                     'lab-config-feedforward')

# Create the population, which is the top-level object for a NEAT run.
p = neat.Population(config)

# Add a stdout reporter to show progress in the terminal.
p.add_reporter(neat.StdOutReporter(False))

# Run until a solution is found.
winner = p.run(eval_genomes,number_generations)

# Display the winning genome.
print('\nBest genome:\n{!s}'.format(winner))

# Show output of the most fit genome against training data.
print('\nOutput:')
winner_net = neat.nn.FeedForwardNetwork.create(winner, config)
for xi, xo in zip(xor_inputs, xor_outputs):
    output = winner_net.activate(xi)
    print("  input {!r}, expected output {!r}, got {!r}".format(xi, xo, output))
    



 ****** Running generation 0 ****** 

Population's average fitness: 2.25214 stdev: 0.38083
Best fitness: 2.99735 - size: (1, 2) - species 1 - id 52
Average adjusted fitness: 0.606
Mean genetic distance 1.167, standard deviation 0.423
Population of 150 members in 1 species
Total extinctions: 0
Generation time: 0.015 sec

 ****** Running generation 1 ****** 

Population's average fitness: 2.32625 stdev: 0.32419
Best fitness: 2.99932 - size: (1, 2) - species 1 - id 230
Average adjusted fitness: 0.598
Mean genetic distance 1.256, standard deviation 0.482
Population of 150 members in 1 species
Total extinctions: 0
Generation time: 0.009 sec (0.012 average)

 ****** Running generation 2 ****** 

Population's average fitness: 2.36521 stdev: 0.36209
Best fitness: 2.99964 - size: (1, 2) - species 1 - id 445
Average adjusted fitness: 0.678
Mean genetic distance 1.316, standard deviation 0.445
Population of 150 members in 1 species
Total extinctions: 0
Generation time: 0.009 sec (0.011 average)


Mean genetic distance 2.330, standard deviation 1.123
Population of 151 members in 6 species
Total extinctions: 0
Generation time: 0.014 sec (0.016 average)

 ****** Running generation 40 ****** 

Population's average fitness: 2.38236 stdev: 0.47029
Best fitness: 3.26240 - size: (3, 4) - species 5 - id 5469
Average adjusted fitness: 0.456
Mean genetic distance 2.469, standard deviation 1.238
Population of 150 members in 6 species
Total extinctions: 0
Generation time: 0.014 sec (0.015 average)

 ****** Running generation 41 ****** 

Population's average fitness: 2.33537 stdev: 0.47851
Best fitness: 3.30484 - size: (4, 5) - species 5 - id 6026
Average adjusted fitness: 0.542
Mean genetic distance 2.394, standard deviation 1.152
Population of 150 members in 6 species
Total extinctions: 0
Generation time: 0.014 sec (0.015 average)

 ****** Running generation 42 ****** 

Population's average fitness: 2.32379 stdev: 0.47295
Best fitness: 3.30484 - size: (4, 5) - species 5 - id 6026
Average a

Mean genetic distance 2.993, standard deviation 1.672
Population of 149 members in 9 species
Total extinctions: 0
Generation time: 0.023 sec (0.019 average)

 ****** Running generation 67 ****** 

Population's average fitness: 2.34063 stdev: 0.50191
Best fitness: 3.33147 - size: (5, 4) - species 11 - id 8703
Average adjusted fitness: 0.558
Mean genetic distance 3.081, standard deviation 1.683
Population of 148 members in 8 species
Total extinctions: 0
Generation time: 0.019 sec (0.019 average)

 ****** Running generation 68 ****** 

Population's average fitness: 2.40496 stdev: 0.51432
Best fitness: 3.33147 - size: (5, 4) - species 11 - id 8703
Average adjusted fitness: 0.580
Mean genetic distance 3.129, standard deviation 1.702
Population of 149 members in 8 species
Total extinctions: 0
Generation time: 0.018 sec (0.019 average)

 ****** Running generation 69 ****** 

Population's average fitness: 2.42128 stdev: 0.49841
Best fitness: 3.33147 - size: (5, 4) - species 11 - id 8703
Averag

In the results of the evolution, see the description of the "Best genome". You can see that the genome is separated between Nodes and Connections. For each node, the bias and activation function are defined. For each connection, the outgoing and ingoing nodes are defined as well as the weights. 

Run the following two cells to visualize this "winner" genome. 

In [3]:
import graphviz

def draw_net_2(config, genome, view=False, filename=None, node_names=None, show_disabled=True, prune_unused=False,
             node_colors=None, fmt='svg'):
    """ Receives a genome and draws a neural network with arbitrary topology. """
    # Attributes for network nodes.
    if graphviz is None:
        warnings.warn("This display is not available due to a missing optional dependency (graphviz)")
        return

    if node_names is None:
        node_names = {}

    assert type(node_names) is dict

    if node_colors is None:
        node_colors = {}

    assert type(node_colors) is dict

    node_attrs = {
        'shape': 'circle',
        'fontsize': '9',
        'height': '0.2',
        'width': '0.2'}

    dot = graphviz.Digraph(format=fmt, node_attr=node_attrs)

    inputs = set()
    for k in config.genome_config.input_keys:
        inputs.add(k)
        name = node_names.get(k, str(k))
        input_attrs = {'style': 'filled',
                       'shape': 'box'}
        input_attrs['fillcolor'] = node_colors.get(k, 'lightgray')
        dot.node(name, _attributes=input_attrs)

    outputs = set()
    for k in config.genome_config.output_keys:
        outputs.add(k)
        name = node_names.get(k, str(k))
        node_attrs = {'style': 'filled'}
        node_attrs['fillcolor'] = node_colors.get(k, 'lightblue')

        dot.node(name, _attributes=node_attrs)

    if prune_unused:
        connections = set()
        for cg in genome.connections.values():
            if cg.enabled or show_disabled:
                connections.add((cg.in_node_id, cg.out_node_id))

        used_nodes = copy.copy(outputs)
        pending = copy.copy(outputs)
        while pending:
            new_pending = set()
            for a, b in connections:
                if b in pending and a not in used_nodes:
                    new_pending.add(a)
                    used_nodes.add(a)
            pending = new_pending
    else:
        used_nodes = set(genome.nodes.keys())

    for n in used_nodes:
        if n in inputs or n in outputs:
            continue

        attrs = {'style': 'filled',
                 'fillcolor': node_colors.get(n, 'white')}
        dot.node(str(n), _attributes=attrs)

    for cg in genome.connections.values():
        if cg.enabled or show_disabled:
            #if cg.input not in used_nodes or cg.output not in used_nodes:
            #    continue
            input, output = cg.key
            a = node_names.get(input, str(input))
            b = node_names.get(output, str(output))
            style = 'solid' if cg.enabled else 'dotted'
            color = 'green' if cg.weight > 0 else 'red'
            width = str(0.1 + abs(cg.weight / 5.0))
            dot.edge(a, b, _attributes={'style': style, 'color': color, 'penwidth': width})

    return dot.source


In [4]:
import pygraphviz

def draw_net(config, genome, view=False, filename=None, node_names=None, show_disabled=True, prune_unused=False,
             node_colors=None, fmt='svg'):
    """ Receives a genome and draws a neural network with arbitrary topology. """
    # Attributes for network nodes.
    if pygraphviz is None:
        warnings.warn("This display is not available due to a missing optional dependency (graphviz)")
        return

    if node_names is None:
        node_names = {}

    assert type(node_names) is dict

    if node_colors is None:
        node_colors = {}

    assert type(node_colors) is dict

    node_attrs = {
        'shape': 'circle',
        'fontsize': '9',
        'height': '0.2',
        'width': '0.2'}

    dot = pygraphviz.AGraph(format=fmt, node_attr=node_attrs)

    inputs = set()
    for k in config.genome_config.input_keys:
        inputs.add(k)
        name = node_names.get(k, str(k))
        input_attrs = {'style': 'filled',
                       'shape': 'box'}
        input_attrs['fillcolor'] = node_colors.get(k, 'lightgray')
        dot.add_node(name, _attributes=input_attrs)

    outputs = set()
    for k in config.genome_config.output_keys:
        outputs.add(k)
        name = node_names.get(k, str(k))
        node_attrs = {'style': 'filled'}
        node_attrs['fillcolor'] = node_colors.get(k, 'lightblue')

        dot.add_node(name, _attributes=node_attrs)

    if prune_unused:
        connections = set()
        for cg in genome.connections.values():
            if cg.enabled or show_disabled:
                connections.add((cg.in_node_id, cg.out_node_id))

        used_nodes = copy.copy(outputs)
        pending = copy.copy(outputs)
        while pending:
            new_pending = set()
            for a, b in connections:
                if b in pending and a not in used_nodes:
                    new_pending.add(a)
                    used_nodes.add(a)
            pending = new_pending
    else:
        used_nodes = set(genome.nodes.keys())

    for n in used_nodes:
        if n in inputs or n in outputs:
            continue

        attrs = {'style': 'filled',
                 'fillcolor': node_colors.get(n, 'white')}
        dot.add_node(str(n), _attributes=attrs)

    for cg in genome.connections.values():
        if cg.enabled or show_disabled:
            #if cg.input not in used_nodes or cg.output not in used_nodes:
            #    continue
            input, output = cg.key
            a = node_names.get(input, str(input))
            b = node_names.get(output, str(output))
            style = 'solid' if cg.enabled else 'dotted'
            color = 'green' if cg.weight > 0 else 'red'
            width = str(0.1 + abs(cg.weight / 5.0))
            dot.add_edge(a, b, _attributes={'style': style, 'color': color, 'penwidth': width})

    dot.draw("neat_nn.png", prog='dot')
    return dot.string()


In [5]:
print(draw_net(config, winner, view=True))

strict graph "" {
	graph [format=svg,
		node_attr="{'shape': 'circle', 'fontsize': '9', 'height': '0.2', 'width': '0.2'}"
	];
	-1	 [_attributes="{'style': 'filled', 'shape': 'box', 'fillcolor': 'lightgray'}"];
	590	 [_attributes="{'style': 'filled', 'fillcolor': 'white'}"];
	-1 -- 590	 [_attributes="{'style': 'solid', 'color': 'red', 'penwidth': '0.8274292458232201'}"];
	0	 [_attributes="{'style': 'filled', 'fillcolor': 'lightblue'}"];
	590 -- 0	 [_attributes="{'style': 'solid', 'color': 'green', 'penwidth': '1.0468176227071122'}"];
	-2	 [_attributes="{'style': 'filled', 'shape': 'box', 'fillcolor': 'lightgray'}"];
	-2 -- 590	 [_attributes="{'style': 'solid', 'color': 'green', 'penwidth': '0.5909903396764201'}"];
	2732	 [_attributes="{'style': 'filled', 'fillcolor': 'white'}"];
	-2 -- 2732	 [_attributes="{'style': 'solid', 'color': 'green', 'penwidth': '0.30000000000000004'}"];
	2732 -- 0	 [_attributes="{'style': 'solid', 'color': 'red', 'penwidth': '0.38035917503901473'}"];
}



You can use the code generated above to visualize the evolved network in a graphviz environment, like that one available in http://www.webgraphviz.com. You just need to copy and paste the code.

# Exercise 1

A multiplexer is a device that allows two or more digital input signals to be selected. The multiplexer problem has been extensively used in AI. We can represent a multipler as a function defined on a vector or n+2^n bits. The function uses the first n bits to decode which of the following 2^n bits should be given as output.

For example, a multipler of n=2 has 2+2^2=6 bits. The multiplexer function would works as follows:

f([0,1,1,0,1,1]) = 0.  The first two bits are used to decode the index, ind=2*0+1=1. The value of the variable in the position ind+2 is the output. In this example v[3]=0


Other examples:
f([0,1,1,1,1,1]) = 1.
f([0,0,1,0,0,0]) = 1.
f([1,1,1,1,1,0]) = 0.

1. Use NEAT to evolve a neural network that computes the multiplexer function for n=2.
2. After running the function modify the number of hidden units in the configuration file
2. Make it a fitness minimization problem (you will have to change the config file, and have another approach in the evaluation function)
3. Visualize the network
4. (Optional) Implement a function that returns *n* samples of a *m*-mux problem. Then test NEAT with the data produced by said function (*n* and *m* are parameters of the function and the NEAT algorithm).


Suggestions:

- Reuse the code from the previous example modifying the definition of the fitness function. The maximum of this function will be 64 (when the 2^6 configurations are correctly predicted).
- Reuse the previous configuration file (with a different name) and update the number of inputs
- You can modify other parameters of the configuration file such as the population size or the probability of adding new nodes and connections. 

In [27]:
from copy import deepcopy



def build_entries(entries, v, i, n):
    if i < n:
        u = v.copy()
        u[i] = 0
        build_entries(entries, u, i + 1, n)
        u[i] = 1
        build_entries(entries, u, i + 1, n)
    else:
        entries.append(v)

        
n = 6
v = [None for _ in range(n)]
entries = []
entries.append([0 for i in range(n)])
build_entries(entries, v, 0, n)


def build_outputs(entries):
    outputs = []
    m = len(entries)
    for v in entries:
        i = v[0]*2 + v[1]
        outputs.append(v[i])
    return outputs


outputs = build_outputs(entries)

inputs = [tuple(x) for x in entries]
outputs = [(x,) for x in outputs]


[(0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (0,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (1,), (0,), (0,), (0,), (0,), (1,), (1,), (1,), (1,), (0,), (0,), (0,), (0,), (1,), (1,), (1,), (1,)]


In [34]:


number_generations = 100


def eval_genomes(genomes, config):
    for genome_id, genome in genomes:
        genome.fitness = 4
        net = neat.nn.FeedForwardNetwork.create(genome, config)

        for xi, xo in zip(entries, outputs):
            output = net.activate(xi)
            genome.fitness -= (output[0] - xo[0]) ** 2


# Load configuration.
config = neat.Config(neat.DefaultGenome, neat.DefaultReproduction, neat.DefaultSpeciesSet, neat.DefaultStagnation,
                     'config-decoder')

# Create the population, which is the top-level object for a NEAT run.
p = neat.Population(config)

# Add a stdout reporter to show progress in the terminal.
p.add_reporter(neat.StdOutReporter(False))

# Run until a solution is found.
winner = p.run(eval_genomes, number_generations)

# Display the winning genome.
print('\nBest genome:\n{!s}'.format(winner))

# Show output of the most fit genome against training data.
print('\nOutput:')
winner_net = neat.nn.FeedForwardNetwork.create(winner, config)
for xi, xo in zip(entries, outputs):
    output = winner_net.activate(xi)
    print("  input {!r}, expected output {!r}, got {!r}".format(xi, xo, output))



 ****** Running generation 0 ****** 

Population's average fitness: -25.86028 stdev: 4.39532
Best fitness: -12.63617 - size: (1, 6) - species 1 - id 128
Average adjusted fitness: 0.422
Mean genetic distance 1.036, standard deviation 0.386
Population of 150 members in 1 species
Total extinctions: 0
Generation time: 0.038 sec

 ****** Running generation 1 ****** 

Population's average fitness: -23.00553 stdev: 5.57748
Best fitness: -9.42606 - size: (1, 6) - species 1 - id 242
Average adjusted fitness: 0.446
Mean genetic distance 1.204, standard deviation 0.427
Population of 150 members in 1 species
Total extinctions: 0
Generation time: 0.038 sec (0.038 average)

 ****** Running generation 2 ****** 

Population's average fitness: -20.82119 stdev: 6.02670
Best fitness: -5.81160 - size: (1, 4) - species 1 - id 314
Average adjusted fitness: 0.405
Mean genetic distance 1.427, standard deviation 0.401
Population of 150 members in 1 species
Total extinctions: 0
Generation time: 0.078 sec (0.05

Population's average fitness: -15.10737 stdev: 8.01499
Best fitness: -4.00001 - size: (5, 8) - species 1 - id 3549
Average adjusted fitness: 0.608
Mean genetic distance 1.871, standard deviation 0.313
Population of 150 members in 2 species
Total extinctions: 0
Generation time: 0.048 sec (0.048 average)

 ****** Running generation 25 ****** 

Population's average fitness: -17.18511 stdev: 8.23936
Best fitness: -4.00001 - size: (5, 8) - species 1 - id 3549
Average adjusted fitness: 0.486
Mean genetic distance 1.811, standard deviation 0.400
Population of 150 members in 2 species
Total extinctions: 0
Generation time: 0.048 sec (0.049 average)

 ****** Running generation 26 ****** 

Population's average fitness: -15.25825 stdev: 8.06431
Best fitness: -4.00001 - size: (5, 8) - species 2 - id 3549
Average adjusted fitness: 0.545
Mean genetic distance 1.876, standard deviation 0.389
Population of 150 members in 2 species
Total extinctions: 0
Generation time: 0.042 sec (0.049 average)

 ******

Population's average fitness: -14.36322 stdev: 9.19007
Best fitness: -4.00000 - size: (4, 6) - species 1 - id 7681
Average adjusted fitness: 0.564
Mean genetic distance 2.517, standard deviation 0.802
Population of 149 members in 4 species
Total extinctions: 0
Generation time: 0.057 sec (0.056 average)

 ****** Running generation 53 ****** 

Population's average fitness: -13.63836 stdev: 8.67436
Best fitness: -4.00000 - size: (4, 6) - species 1 - id 7681
Average adjusted fitness: 0.597
Mean genetic distance 2.520, standard deviation 0.774
Population of 150 members in 4 species
Total extinctions: 0
Generation time: 0.054 sec (0.056 average)

 ****** Running generation 54 ****** 

Population's average fitness: -13.57134 stdev: 9.19083
Best fitness: -4.00000 - size: (4, 6) - species 1 - id 7681
Average adjusted fitness: 0.675
Mean genetic distance 2.583, standard deviation 0.735
Population of 150 members in 4 species
Total extinctions: 0
Generation time: 0.051 sec (0.056 average)

 ******

Population's average fitness: -13.17322 stdev: 9.27433
Best fitness: -4.00000 - size: (3, 7) - species 8 - id 10735
Average adjusted fitness: 0.574
Mean genetic distance 2.823, standard deviation 0.831
Population of 149 members in 9 species
Total extinctions: 0
Generation time: 0.058 sec (0.059 average)

 ****** Running generation 77 ****** 

Population's average fitness: -12.18809 stdev: 9.27188
Best fitness: -4.00000 - size: (3, 7) - species 5 - id 10735
Average adjusted fitness: 0.645
Mean genetic distance 2.793, standard deviation 0.784
Population of 150 members in 9 species
Total extinctions: 0
Generation time: 0.057 sec (0.060 average)

 ****** Running generation 78 ****** 

Population's average fitness: -11.73102 stdev: 9.04213
Best fitness: -4.00000 - size: (4, 7) - species 8 - id 11269
Average adjusted fitness: 0.703
Mean genetic distance 2.796, standard deviation 0.807
Population of 150 members in 10 species
Total extinctions: 0
Generation time: 0.057 sec (0.060 average)

 **

## Exercise 2 

1. Using NEAT, evolve a network that paints a black-and-white image. The network receives as input the coordinates (x,y) and outputs a binary value that represents whether the pixel is filled or not. Use the image in the following cell.



In [35]:
dimension = 13
cross_image = np.zeros((dimension,dimension))
cross_image[5:8,:] = 1
cross_image[:,5:8] = 1
print(cross_image)

[[0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0.]]


## Other software for implementing the evolution of NNs

DEAP (http://deap.readthedocs.io/en/master/index.html) is another flexible library for evolutionary algorithms (genetic algorithms and genetic programming). 

You may use DEAP to find the optimal hyperparameters of your model.

Below there is one example of how to define a simple evolutionary algorith for solving the OneMax function. See how the components of the algorithm are defined. 

In [ ]:
from deap import algorithms
from deap import base
from deap import creator
from deap import tools
import random
import numpy as np


creator.create("FitnessMax", base.Fitness, weights=(1.0,))  # 1.0 for maximizing, -1.0 for minimizing
creator.create("Individual", list, fitness=creator.FitnessMax)


toolbox = base.Toolbox()
# Attribute generator 
toolbox.register("attr_bool", random.randint, 0, 1)
# Structure initializers
toolbox.register("individual", tools.initRepeat, creator.Individual, 
    toolbox.attr_bool, 100)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)


def evalOneMax(individual):
    return sum(individual),


toolbox.register("evaluate", evalOneMax)
toolbox.register("mate", tools.cxTwoPoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)

def main():
    pop = toolbox.population(n=300)
    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("avg", np.mean)
    stats.register("std", np.std)
    stats.register("min", np.min)
    stats.register("max", np.max)
    
    pop, log = algorithms.eaSimple(pop, toolbox, cxpb=0.5, mutpb=0.2, ngen=40, 
                                   stats=stats, halloffame=hof, verbose=True)
main()
    


## Exercise 3

1. Define a simple tensorflow NN model where the number of neurons in each layer are defined by variables. You can use the code implemented in Exercise 6 of Lab5, where a parametrized function is used to create MLPs.
2. Using DEAP, define an algorithm that optimizes the hyper-parameters of your model for the complete MNIST problem. 

In [ ]:
(X_train_mnist, y_train_mnist), (X_test_mnist, y_test_mnist) = mnist.load_data()

X_train_mnist = np.reshape(X_train_mnist, (-1, 784))
X_test_mnist = np.reshape(X_test_mnist, (-1, 784))

enc = OneHotEncoder(sparse=False)
# Transform the labels in y_train_mnist and y_test_mnist to one hot encoding

X_train_mnist = X_train_mnist/255.  # Normalize the data
X_test_mnist = X_test_mnist/255.  # Normalize the data
X_train_mnist = X_train_mnist[:10000]  # Select a subset of the data for lighter training


In [ ]:
def createMLP(in_size, h_layers, out_size):
    """
    inp: An integer. This will be the size of the data input.
    h_layers: A list of integers. Each integer represents the number of neurons in a hidden layer. For example,
        h_layers = [40, 30, 50, 60] will result in an MLP with four hidden layers.
    outp: An integer. This will be the size of the predicted data.
    """
    # These two lists must store all variables created in this function
    weights = []
    biases = []
    
    tf.reset_default_graph()
    
    X = tf.placeholder("float", shape=[___], name="X")
    Y = tf.placeholder("float", shape=[___], name="y")
    
    ws = [tf.Variable(tf.random_normal((___)), name="weights_in")]
    bs = [tf.Variable(tf.random_normal((___)), name="bias_in")]

    layer = tf.add(tf.matmul(X, ws[0]), bs[0])
    
    for i in range(1, len(h_layers)):

        ws += [___]
        bs += [___]
        
        layer = ___
        
    ws = [___]
    bs = [___]

    return tf.add(tf.matmul(___), ___), X, Y

In [ ]:
def create_optimizer(mlp, Y):
    loss = ___

    learning_rate = 0.0001

    adam = tf.train.AdamOptimizer(learning_rate)

    return adam.minimize(loss), loss


In [ ]:
def train_test_model(optimizer, loss, X_train, y_train, X_test, y_test, X, Y):
    
    init = tf.global_variables_initializer()
    training_epochs = 1000
    batch_size = 100
    aux_ind = 0
    
    with tf.Session(config=tf.ConfigProto(allow_soft_placement=True, log_device_placement=True)) as sess:

        sess.run(init)

        for epoch in range(training_epochs):
            aux_ind = (aux_ind + batch_size) % X_train.shape[0]
            batch = X_train[aux_ind:aux_ind+batch_size], y_train[aux_ind:aux_ind+batch_size]
            sess.run(___, feed_dict={___})  # Perform the learning step

        return sess.run(loss, feed_dict={X: X_test, Y: y_test})

In [ ]:
def eval_model(ind):

    ind_mlp, X, Y = createMLP(___, ind, ___)
    opt, loss = create_optimizer(ind_mlp, Y)
    return train_test_model(opt, loss, X_train_mnist, y_train_mnist, X_test_mnist, y_test_mnist, X, Y), 

In [ ]:
from deap import algorithms
from deap import base
from deap import creator
from deap import tools
import random
import numpy as np


creator.create("Fitness", base.Fitness, weights=(___,))  # 1.0 for maximizing, -1.0 for minimizing
creator.create("Individual", list, fitness=creator.Fitness)


toolbox = base.Toolbox()
# Attribute generator 
toolbox.register("layers", random.randint, ___, ___)
# Structure initializers
toolbox.register("individual", tools.initRepeat, creator.Individual, toolbox.layers, ___)
toolbox.register("population", tools.initRepeat, list, toolbox.individual)

toolbox.register("evaluate", eval_model)
toolbox.register("mate", tools.cxOnePoint)
toolbox.register("mutate", tools.mutFlipBit, indpb=0.05)
toolbox.register("select", tools.selTournament, tournsize=3)

def main():
    pop = toolbox.population(n=___)
    hof = tools.HallOfFame(1)
    stats = tools.Statistics(lambda ind: ind.fitness.values)
    stats.register("avg", np.mean)
    stats.register("std", np.std)
    stats.register("min", np.min)
    stats.register("max", np.max)
    
    pop, log = algorithms.eaSimple(pop, toolbox, cxpb=0.5, mutpb=0.2, ngen=___, stats=stats, halloffame=hof, verbose=True)
    
    return hof[0]

main()

